# Generated by Django 4.0.4 on 2022-05-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_depart', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(blank=True, null=True, verbose_name='Entrada Data/Hora')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Saida Data/Hora')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='NF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=9)),
                ('dados', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Folha_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_extra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.escolaridade'),
        ),
    ]
