# Generated by Django 4.0.4 on 2022-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
