# Generated by Django 4.0.4 on 2022-05-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_escolaridade_nivel_escolaridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
            ],
        ),
    ]
