# Generated by Django 4.0.4 on 2022-05-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_escolaridade_nivel_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf',
            name='data_entrada',
            field=models.DateTimeField(auto_now=False, null=True),
        ),
    ]
