# Generated by Django 4.0.4 on 2022-05-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_nf_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
