# Generated by Django 4.0.4 on 2022-05-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_alter_nf_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='nf',
            name='departamento',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='rh.departamento'),
        ),
    ]
