# Generated by Django 4.0.4 on 2022-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_folha_pagamento_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folha_pagamento',
            name='hora_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
